FROM jenkins/jenkins:lts-jdk17

# Instal Docker CLI
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    docker.io \
    && rm -rf /var/lib/apt/lists/*
# Tambahkan user 'jenkins' ke grup 'docker'
RUN usermod -aG docker jenkins
USER jenkins